In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

https://www.kaggle.com/datasets/amanalisiddiqui/fraud-detection-dataset?resource=download

In [13]:
main_df = pd.read_csv("AIML Dataset.csv")
print(main_df.shape)
print(main_df.columns.tolist())
print(main_df.head())

(6362620, 11)
['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig', 'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud', 'isFlaggedFraud']
   step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72
2     1  TRANSFER    181.00  C1305486145          181.0            0.00
3     1  CASH_OUT    181.00   C840083671          181.0            0.00
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud
0  M1979787155             0.0             0.0        0               0
1  M2044282225             0.0             0.0        0               0
2   C553264065             0.0             0.0        1               0
3    C38997010         21182.0             0.0        1               0
4  M1230701703             0.0             0.0        0               0

In [14]:
main_df.columns.tolist()

['step',
 'type',
 'amount',
 'nameOrig',
 'oldbalanceOrg',
 'newbalanceOrig',
 'nameDest',
 'oldbalanceDest',
 'newbalanceDest',
 'isFraud',
 'isFlaggedFraud']

step — time unit


type — PAYMENT, TRANSFER, CASH_OUT, CASH_IN, DEBIT


amount — transaction amount


nameOrig — sender


oldbalanceOrg — sender's balance before


newbalanceOrig — sender's balance after


nameDest — receiver


oldbalanceDest — receiver's balance before


newbalanceDest — receiver's balance after


isFraud — target variable 


isFlaggedFraud — flagged by system

In [34]:
main_df

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.00,0.00,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.00,0.00,0,0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.00,0.00,1,0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.00,0.00,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.00,0.00,0,0
...,...,...,...,...,...,...,...,...,...,...,...
6362615,743,CASH_OUT,339682.13,C786484425,339682.13,0.00,C776919290,0.00,339682.13,1,0
6362616,743,TRANSFER,6311409.28,C1529008245,6311409.28,0.00,C1881841831,0.00,0.00,1,0
6362617,743,CASH_OUT,6311409.28,C1162922333,6311409.28,0.00,C1365125890,68488.84,6379898.11,1,0
6362618,743,TRANSFER,850002.52,C1685995037,850002.52,0.00,C2080388513,0.00,0.00,1,0
6362619,743,CASH_OUT,850002.52,C1280323807,850002.52,0.00,C873221189,6510099.11,7360101.63,1,0

In [35]:
print(main_df['isFraud'].value_counts())
print(main_df['type'].value_counts())

isFraud
0    6354407
1       8213
Name: count, dtype: int64
type
CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: count, dtype: int64

In [36]:
main_df.isna().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [37]:
main_df['amount'].describe().astype(int)

count     6362620
mean       179861
std        603858
min             0
25%         13389
50%         74871
75%        208721
max      92445516
Name: amount, dtype: int64

In [38]:
account_df = pd.read_csv(r"C:\Users\ayman\Documents\Github\fraud_detection\data\account.csv", sep=';')
card_df = pd.read_csv(r"C:\Users\ayman\Documents\Github\fraud_detection\data\card.csv", sep=';')
client_df = pd.read_csv(r"C:\Users\ayman\Documents\Github\fraud_detection\data\client.csv", sep=';')
disp_df = pd.read_csv(r"C:\Users\ayman\Documents\Github\fraud_detection\data\disp.csv", sep=';')
district_df = pd.read_csv(r"C:\Users\ayman\Documents\Github\fraud_detection\data\district.csv", sep=';')
loan_df = pd.read_csv(r"C:\Users\ayman\Documents\Github\fraud_detection\data\loan.csv", sep=';')
order_df = pd.read_csv(r"C:\Users\ayman\Documents\Github\fraud_detection\data\order.csv", sep=';')
trans_df = pd.read_csv(r"C:\Users\ayman\Documents\Github\fraud_detection\data\trans.csv", sep=';')

C:\Users\ayman\AppData\Local\Temp\ipykernel_25416\313453794.py:8: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  trans_df = pd.read_csv(r"C:\Users\ayman\Documents\Github\fraud_detection\data\trans.csv", sep=';')

In [20]:
print("account:", account_df.shape)
print("card:", card_df.shape)
print("client:", client_df.shape)
print("disp:", disp_df.shape)
print("district:", district_df.shape)
print("loan:", loan_df.shape)
print("order:", order_df.shape)
print("trans:", trans_df.shape)

account: (4500, 4)
card: (892, 4)
client: (5369, 3)
disp: (5369, 4)
district: (77, 16)
loan: (682, 7)
order: (6471, 6)
trans: (1056320, 10)

In [21]:
account_df

      account_id  district_id         frequency    date
0            576           55  POPLATEK MESICNE  930101
1           3818           74  POPLATEK MESICNE  930101
2            704           55  POPLATEK MESICNE  930101
3           2378           16  POPLATEK MESICNE  930101
4           2632           24  POPLATEK MESICNE  930102
...          ...          ...               ...     ...
4495         124           55  POPLATEK MESICNE  971228
4496        3958           59  POPLATEK MESICNE  971228
4497         777           30  POPLATEK MESICNE  971228
4498        1573           63  POPLATEK MESICNE  971229
4499        3276            1  POPLATEK MESICNE  971229

[4500 rows x 4 columns]

In [22]:
card_df

     card_id  disp_id     type           issued
0       1005     9285  classic  931107 00:00:00
1        104      588  classic  940119 00:00:00
2        747     4915  classic  940205 00:00:00
3         70      439  classic  940208 00:00:00
4        577     3687  classic  940215 00:00:00
..       ...      ...      ...              ...
887      125      694     gold  981226 00:00:00
888      674     4360  classic  981228 00:00:00
889      322     2063  classic  981228 00:00:00
890      685     4467  classic  981229 00:00:00
891      635     4083  classic  981229 00:00:00

[892 rows x 4 columns]

In [32]:
card_df['type'].value_counts()
# what are the different types of cards? Are there any patterns in the types of cards that are more likely to be associated with fraud?

type
classic    659
junior     145
gold        88
Name: count, dtype: int64

In [23]:
loan_df

     loan_id  account_id    date  amount  duration  payments status
0       5314        1787  930705   96396        12    8033.0      B
1       5316        1801  930711  165960        36    4610.0      A
2       6863        9188  930728  127080        60    2118.0      A
3       5325        1843  930803  105804        36    2939.0      A
4       7240       11013  930906  274740        60    4579.0      A
..       ...         ...     ...     ...       ...       ...    ...
677     4989         105  981205  352704        48    7348.0      C
678     5221        1284  981205   52512        12    4376.0      C
679     6402        6922  981206  139488        24    5812.0      C
680     5346        1928  981206   55632        24    2318.0      C
681     6748        8645  981208  240900        60    4015.0      C

[682 rows x 7 columns]

In [24]:
print(loan_df['status'].value_counts())

status
C    403
A    203
D     45
B     31
Name: count, dtype: int64

So B and D are the problem loans — either already defaulted or currently behind on payments. That's why we set them to 1 (default) and A and C to 0 (good).

In [25]:
# Create binary target
loan_df['default'] = loan_df['status'].apply(lambda x: 1 if x in ['B', 'D'] else 0)
print(loan_df['default'].value_counts())

default
0    606
1     76
Name: count, dtype: int64

In [26]:
trans_df

,trans_id,account_id,date,type,operation,amount,balance,k_symbol,bank,account
0,695247,2378,930101,PRIJEM,VKLAD,700.0,700.0,NaN,NaN,NaN
1,171812,576,930101,PRIJEM,VKLAD,900.0,900.0,NaN,NaN,NaN
2,207264,704,930101,PRIJEM,VKLAD,1000.0,1000.0,NaN,NaN,NaN
3,1117247,3818,930101,PRIJEM,VKLAD,600.0,600.0,NaN,NaN,NaN
4,579373,1972,930102,PRIJEM,VKLAD,400.0,400.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1056315,3626622,2906,981231,PRIJEM,NaN,62.3,13729.4,UROK,NaN,NaN
1056316,3627616,2935,981231,PRIJEM,NaN,81.3,19544.9,UROK,NaN,NaN
1056317,3625403,2869,981231,PRIJEM,NaN,60.2,14638.2,UROK,NaN,NaN
1056318,3626683,2907,981231,PRIJEM,NaN,107.5,23453.0,UROK,NaN,NaN
1056319,3626540,2902,981231,PRIJEM,NaN,164.1,41642.9,UROK,NaN,NaN

bank names hidden for privacy

In [ ]:
trans_df['bank'].value_counts()
# information about the bank is missing for 1,000,000 transactions, which is a significant portion of the data. This could impact our analysis and modeling, as we may not be able to leverage any potential insights related to the bank variable. We will need to consider how to handle this missing data, such as imputation or excluding it from certain analyses.

bank
QR    22285
AB    21720
ST    21711
YZ    21582
GH    21499
EF    21293
KL    21234
UV    21167
OP    21094
IJ    20525
WX    20178
MN    19623
CD    19597
Name: count, dtype: int64

In [33]:
order_df

      order_id  account_id bank_to  account_to  amount  k_symbol
0        29401           1      YZ    87144583  2452.0      SIPO
1        29402           2      ST    89597016  3372.7      UVER
2        29403           2      QR    13943797  7266.0      SIPO
3        29404           3      WX    83084338  1135.0      SIPO
4        29405           3      CD    24485939   327.0
...        ...         ...     ...         ...     ...       ...
6466     46334       11362      YZ    70641225  4780.0      SIPO
6467     46335       11362      MN    78507822    56.0
6468     46336       11362      ST    40799850   330.0  POJISTNE
6469     46337       11362      KL    20009470   129.0
6470     46338       11362      MN    61540514  5392.0      UVER

[6471 rows x 6 columns]