In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import os

In [2]:
main_df = pd.read_csv("/Users/utkuseyithanoglu/Desktop/1999 czech banking/fraud_detection/data/account.csv",sep=";")

In [3]:
main_df

      account_id  district_id         frequency    date
0            576           55  POPLATEK MESICNE  930101
1           3818           74  POPLATEK MESICNE  930101
2            704           55  POPLATEK MESICNE  930101
3           2378           16  POPLATEK MESICNE  930101
4           2632           24  POPLATEK MESICNE  930102
...          ...          ...               ...     ...
4495         124           55  POPLATEK MESICNE  971228
4496        3958           59  POPLATEK MESICNE  971228
4497         777           30  POPLATEK MESICNE  971228
4498        1573           63  POPLATEK MESICNE  971229
4499        3276            1  POPLATEK MESICNE  971229

[4500 rows x 4 columns]

In [4]:
main_df.isna().sum()

account_id     0
district_id    0
frequency      0
date           0
dtype: int64

In [5]:
main_df['account_id'].value_counts()

account_id
576     1
6453    1
836     1
3192    1
4389    1
       ..
988     1
3058    1
1958    1
1441    1
3276    1
Name: count, Length: 4500, dtype: int64

In [6]:
main_df1 = pd.read_csv("/Users/utkuseyithanoglu/Desktop/1999 czech banking/fraud_detection/data/card.csv",sep=";")

In [7]:
main_df1

     card_id  disp_id     type           issued
0       1005     9285  classic  931107 00:00:00
1        104      588  classic  940119 00:00:00
2        747     4915  classic  940205 00:00:00
3         70      439  classic  940208 00:00:00
4        577     3687  classic  940215 00:00:00
..       ...      ...      ...              ...
887      125      694     gold  981226 00:00:00
888      674     4360  classic  981228 00:00:00
889      322     2063  classic  981228 00:00:00
890      685     4467  classic  981229 00:00:00
891      635     4083  classic  981229 00:00:00

[892 rows x 4 columns]

In [8]:
main_df2 = pd.read_csv("/Users/utkuseyithanoglu/Desktop/1999 czech banking/fraud_detection/data/client.csv",sep=";")

In [9]:
main_df2

      client_id  birth_number  district_id
0             1        706213           18
1             2        450204            1
2             3        406009            1
3             4        561201            5
4             5        605703            5
...         ...           ...          ...
5364      13955        456030            1
5365      13956        430406            1
5366      13968        680413           61
5367      13971        626019           67
5368      13998        535812           74

[5369 rows x 3 columns]

In [10]:
main_df2 = pd.read_csv("/Users/utkuseyithanoglu/Desktop/1999 czech banking/fraud_detection/data/disp.csv",sep=";")

In [11]:
main_df2

      disp_id  client_id  account_id       type
0           1          1           1      OWNER
1           2          2           2      OWNER
2           3          3           2  DISPONENT
3           4          4           3      OWNER
4           5          5           3  DISPONENT
...       ...        ...         ...        ...
5364    13647      13955       11349      OWNER
5365    13648      13956       11349  DISPONENT
5366    13660      13968       11359      OWNER
5367    13663      13971       11362      OWNER
5368    13690      13998       11382      OWNER

[5369 rows x 4 columns]

In [12]:
district_df = pd.read_csv("/Users/utkuseyithanoglu/Desktop/1999 czech banking/fraud_detection/data/district.csv",sep=";")

In [13]:
district_df

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16
0,1,Hl.m. Praha,Prague,1204953,0,0,0,1,1,100.0,12541,0.29,0.43,167,85677,99107
1,2,Benesov,central Bohemia,88884,80,26,6,2,5,46.7,8507,1.67,1.85,132,2159,2674
2,3,Beroun,central Bohemia,75232,55,26,4,1,5,41.7,8980,1.95,2.21,111,2824,2813
3,4,Kladno,central Bohemia,149893,63,29,6,2,6,67.4,9753,4.64,5.05,109,5244,5892
4,5,Kolin,central Bohemia,95616,65,30,4,1,6,51.4,9307,3.85,4.43,118,2616,3040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,73,Opava,north Moravia,182027,17,49,12,2,7,56.4,8746,3.33,3.74,90,4355,4433
73,74,Ostrava - mesto,north Moravia,323870,0,0,0,1,1,100.0,10673,4.75,5.44,100,18782,18347
74,75,Prerov,north Moravia,138032,67,30,4,2,5,64.6,8819,5.38,5.66,99,4063,4505
75,76,Sumperk,north Moravia,127369,31,32,13,2,7,51.2,8369,4.73,5.88,107,3736,2807
76,77,Vsetin,north Moravia,148545,8,35,12,3,4,53.5,8909,4.01,5.56,113,3460,3590

In [14]:
loan_df = pd.read_csv("/Users/utkuseyithanoglu/Desktop/1999 czech banking/fraud_detection/data/loan.csv",sep=";")

In [15]:
loan_df

     loan_id  account_id    date  amount  duration  payments status
0       5314        1787  930705   96396        12    8033.0      B
1       5316        1801  930711  165960        36    4610.0      A
2       6863        9188  930728  127080        60    2118.0      A
3       5325        1843  930803  105804        36    2939.0      A
4       7240       11013  930906  274740        60    4579.0      A
..       ...         ...     ...     ...       ...       ...    ...
677     4989         105  981205  352704        48    7348.0      C
678     5221        1284  981205   52512        12    4376.0      C
679     6402        6922  981206  139488        24    5812.0      C
680     5346        1928  981206   55632        24    2318.0      C
681     6748        8645  981208  240900        60    4015.0      C

[682 rows x 7 columns]

In [16]:
order_df = pd.read_csv("/Users/utkuseyithanoglu/Desktop/1999 czech banking/fraud_detection/data/order.csv",sep=";")

In [17]:
order_df

      order_id  account_id bank_to  account_to  amount  k_symbol
0        29401           1      YZ    87144583  2452.0      SIPO
1        29402           2      ST    89597016  3372.7      UVER
2        29403           2      QR    13943797  7266.0      SIPO
3        29404           3      WX    83084338  1135.0      SIPO
4        29405           3      CD    24485939   327.0
...        ...         ...     ...         ...     ...       ...
6466     46334       11362      YZ    70641225  4780.0      SIPO
6467     46335       11362      MN    78507822    56.0
6468     46336       11362      ST    40799850   330.0  POJISTNE
6469     46337       11362      KL    20009470   129.0
6470     46338       11362      MN    61540514  5392.0      UVER

[6471 rows x 6 columns]

In [18]:
trans_df= pd.read_csv("/Users/utkuseyithanoglu/Desktop/1999 czech banking/fraud_detection/data/trans.csv",sep=";")

/var/folders/34/1yg1tqgd1b96v45w9k29prnw0000gn/T/ipykernel_37341/1069296151.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  trans_df= pd.read_csv("/Users/utkuseyithanoglu/Desktop/1999 czech banking/fraud_detection/data/trans.csv",sep=";")

In [19]:
trans_df

,trans_id,account_id,date,type,operation,amount,balance,k_symbol,bank,account
0,695247,2378,930101,PRIJEM,VKLAD,700.0,700.0,NaN,NaN,NaN
1,171812,576,930101,PRIJEM,VKLAD,900.0,900.0,NaN,NaN,NaN
2,207264,704,930101,PRIJEM,VKLAD,1000.0,1000.0,NaN,NaN,NaN
3,1117247,3818,930101,PRIJEM,VKLAD,600.0,600.0,NaN,NaN,NaN
4,579373,1972,930102,PRIJEM,VKLAD,400.0,400.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1056315,3626622,2906,981231,PRIJEM,NaN,62.3,13729.4,UROK,NaN,NaN
1056316,3627616,2935,981231,PRIJEM,NaN,81.3,19544.9,UROK,NaN,NaN
1056317,3625403,2869,981231,PRIJEM,NaN,60.2,14638.2,UROK,NaN,NaN
1056318,3626683,2907,981231,PRIJEM,NaN,107.5,23453.0,UROK,NaN,NaN
1056319,3626540,2902,981231,PRIJEM,NaN,164.1,41642.9,UROK,NaN,NaN

In [20]:
trans_df.isna().sum()

trans_id           0
account_id         0
date               0
type               0
operation     183114
amount             0
balance            0
k_symbol      481881
bank          782812
account       760931
dtype: int64